//# DIM DATE: 
DIM_Date = CALENDAR(DATE(2021,01,01),date(2022,12,31))

//# FACT: FACT_Sales

Tổng Doanh số = SUM('FACT_Sales'[Thành tiền])
Class Customer = IF([Rank Sales by Customer]>=100,"C",
                    IF([Rank Sales by Customer]>=50,"B",
                        IF([Rank Sales by Customer]>=10,"A","A+" )))

Doanh số TB Tháng = CALCULATE(AVERAGEX(VALUES('DIM_Date'[Date].[MonthNo]),FACT_Sales[Tổng doanh số]),DATESYTD('DIM_Date'[Date]))
Doanh số TB Ngày = CALCULATE(AVERAGEX(VALUES('DIM_Date'[Date].[Day]),FACT_Sales[Tổng doanh số]),DATESMTD('DIM_Date'[Date]))
Doanh số YTM = CALCULATE(FACT_Sales[Tổng doanh số],DATESYTD(FACT_Sales[DIM_Date]) )


Rank Sales by Categories = RANKX(ALL(FACT_Sales[Mã nhóm]),FACT_Sales[Tổng doanh số])
Rank Sales by Customer = RANKX(ALL(FACT_Sales[Mã Khách hàng]),FACT_Sales[Tổng doanh số])

Sale MoM % = DIVIDE(FACT_Sales[Tổng doanh số]-FACT_Sales[Sales last month],FACT_Sales[Sales last month]) 
Sale YoY % = DIVIDE(FACT_Sales[Doanh số YTM]-FACT_Sales[Sales last year],FACT_Sales[Sales last year]) 

Sales current month = CALCULATE([Tổng doanh số],PARALLELPERIOD('DIM_Date'[Date],0,MONTH ))
Sales last month = CALCULATE([Tổng doanh số],PARALLELPERIOD('DIM_Date'[Date],-1,MONTH ))

Sales last year = CALCULATE([Tổng doanh số],PARALLELPERIOD('DIM_Date'[Date],-1,YEAR ))

Sales last year = CALCULATE([Tổng doanh số],PARALLELPERIOD('DIM_Date'[Date],-1,YEAR ))
Tổng doanh số tháng trước = CALCULATE(FACT_Sales[Tổng doanh số],DATEADD('DIM_Date'[Date],-1,YEAR))
Tổng Đơn hàng trên tháng = CALCULATE(COUNT(FACT_Sales[ID]),DATESMTD('DIM_Date'[Date]))

// RANK CUSTOMER 

Rank Customer = GROUPBY('FACT_Sales','FACT_Sales'[ID Khách hàng],"Tổng doanh số",SUMX(CURRENTGROUP(),FACT_Sales[Thành tiền]))
RANK Customer = RANK.EQ('Rank Customer'[Tổng doanh số],'Rank Customer'[Tổng doanh số],DESC)
Class_Customer = IF('Rank Customer'[RANK Customer]>=100,"C",
                    IF('Rank Customer'[RANK Customer]>=60,"B",
                        IF('Rank Customer'[RANK Customer]>=20,"A",
                            IF('Rank Customer'[RANK Customer]>=10,"A+","VIP"))))


// # RELATIONSHIP
DIM_Date -> FACT_Sales : ID
DIM NameSale -> FACT_Sales: Nhân viên



# BUILD - POWER QUERIES EDITOR
IF(ISBLANK([ID Customer]),[ID Khách hàng],[Tên Khách hàng])

