//# DIM DATE: 
DIM_Date = CALENDAR(DATE(2021,01,01),date(2022,12,31))

//# FACT: FACT_Sales

Tổng Doanh số = SUM('FACT_Sales'[Thành tiền])
Class Customer = IF([Rank Sales by Customer]>=100,"C",
                    IF([Rank Sales by Customer]>=50,"B",
                        IF([Rank Sales by Customer]>=10,"A","A+" )))

Doanh số TB Tháng = CALCULATE(AVERAGEX(VALUES('DIM_Date'[Date].[MonthNo]),FACT_Sales[Tổng doanh số]),DATESYTD('DIM_Date'[Date]))
Doanh số TB Ngày = CALCULATE(AVERAGEX(VALUES('DIM_Date'[Date].[Day]),FACT_Sales[Tổng doanh số]),DATESMTD('DIM_Date'[Date]))
Doanh số YTM = CALCULATE(FACT_Sales[Tổng doanh số],DATESYTD(FACT_Sales[DIM_Date]) )


Rank Sales by Categories = RANKX(ALL(FACT_Sales[Mã nhóm]),FACT_Sales[Tổng doanh số])
Rank Sales by Customer = RANKX(ALL(FACT_Sales[Mã Khách hàng]),FACT_Sales[Tổng doanh số])
//------------------ Sale MoM------------------
Sale MoM % = DIVIDE(FACT_Sales[Tổng doanh số]-FACT_Sales[Sales last month],FACT_Sales[Sales last month]) 
Sales current month = CALCULATE(SUM('FACT_Sales'[Thành tiền]),DATESMTD('DIM_Date'[Date]))       
Sales last month = CALCULATE(SUM('FACT_Sales'[Thành tiền]),PREVIOUSMONTH('DIM_Date'[Date]))   



// RANK CUSTOMER 

Rank Customer = GROUPBY('FACT_Sales','FACT_Sales'[ID Khách hàng],"Tổng doanh số",SUMX(CURRENTGROUP(),FACT_Sales[Thành tiền]))
RANK Customer = RANK.EQ('Rank Customer'[Tổng doanh số],'Rank Customer'[Tổng doanh số],DESC)
Class_Customer = IF('Rank Customer'[RANK Customer]>=100,"C",
                    IF('Rank Customer'[RANK Customer]>=60,"B",
                        IF('Rank Customer'[RANK Customer]>=20,"A",
                            IF('Rank Customer'[RANK Customer]>=10,"A+","VIP"))))
//- --------------- Thứ ngày
Thứ = WEEKDAY('DIM_Date'[Date],1)
Thứ ngày = SWITCH('DIM_Date'[Thứ],
            1,"Chủ nhật",
            2,"Thứ hai",
            3,"Thứ ba",
            4,"Thứ tư",
            5,"Thứ năm",
            6,"Thứ sáu",
            7,"Thứ bảy")



// # RELATIONSHIP
DIM_Date -> FACT_Sales : ID
DIM NameSale -> FACT_Sales: Nhân viên



# BUILD - POWER QUERIES EDITOR
IF(ISBLANK([ID Customer]),[ID Khách hàng],[Tên Khách hàng])

